var hierarchy =
[
    [ "ServidorDeAudios::modelos::ArchivoAudio", "structServidorDeAudios_1_1modelos_1_1ArchivoAudio.html", null ],
    [ "Administrador::dtos::ArchivoAudioDTO", "structAdministrador_1_1dtos_1_1ArchivoAudioDTO.html", null ],
    [ "ServidorDeAudios::dtos::ArchivoAudioDTOOutput", "structServidorDeAudios_1_1dtos_1_1ArchivoAudioDTOOutput.html", null ],
    [ "ServidorMetadataDeAudios::modelos::Audio", "classServidorMetadataDeAudios_1_1modelos_1_1Audio.html", null ],
    [ "Administrador::dtos::AudioAlmacenadoDTO", "structAdministrador_1_1dtos_1_1AudioAlmacenadoDTO.html", null ],
    [ "ServidorDeAudios::dtos::AudioAlmacenadoDTOOutput", "structServidorDeAudios_1_1dtos_1_1AudioAlmacenadoDTOOutput.html", null ],
    [ "Administrador::dtos::AudioAlmacenarDTO", "structAdministrador_1_1dtos_1_1AudioAlmacenarDTO.html", null ],
    [ "ServidorDeAudios::dtos::AudioAlmacenarDTOInput", "structServidorDeAudios_1_1dtos_1_1AudioAlmacenarDTOInput.html", null ],
    [ "ServidorMetadataDeAudios::modelos::AudioBase", "structServidorMetadataDeAudios_1_1modelos_1_1AudioBase.html", [
      [ "ServidorMetadataDeAudios::modelos::Audiolibro", "structServidorMetadataDeAudios_1_1modelos_1_1Audiolibro.html", null ],
      [ "ServidorMetadataDeAudios::modelos::Musica", "structServidorMetadataDeAudios_1_1modelos_1_1Musica.html", null ],
      [ "ServidorMetadataDeAudios::modelos::Podcast", "structServidorMetadataDeAudios_1_1modelos_1_1Podcast.html", null ],
      [ "ServidorMetadataDeAudios::modelos::RuidoBlanco", "structServidorMetadataDeAudios_1_1modelos_1_1RuidoBlanco.html", null ]
    ] ],
    [ "Cliente::dtos::AudioDetalleDTO", "structCliente_1_1dtos_1_1AudioDetalleDTO.html", null ],
    [ "ServidorMetadataDeAudios::dtos::AudioDetalleDTOOutput", "structServidorMetadataDeAudios_1_1dtos_1_1AudioDetalleDTOOutput.html", null ],
    [ "Cliente::dtos::AudioResumenDTO", "structCliente_1_1dtos_1_1AudioResumenDTO.html", null ],
    [ "ServidorMetadataDeAudios::dtos::AudioResumenDTOOutput", "structServidorMetadataDeAudios_1_1dtos_1_1AudioResumenDTOOutput.html", null ],
    [ "ServidorDeEstadisticas::modelos::Conteo", "structServidorDeEstadisticas_1_1modelos_1_1Conteo.html", null ],
    [ "Administrador::capacontroladores::ControladorAdministrador", "structAdministrador_1_1capacontroladores_1_1ControladorAdministrador.html", null ],
    [ "ServidorDeAudios::capacontroladores::ControladorAlmacenamientoAudios", "structServidorDeAudios_1_1capacontroladores_1_1ControladorAlmacenamientoAudios.html", null ],
    [ "Cliente::capacontroladores::ControladorAudios", "structCliente_1_1capacontroladores_1_1ControladorAudios.html", null ],
    [ "ServidorDeEstadisticas::capacontroladores::ControladorEstadisticas", "structServidorDeEstadisticas_1_1capacontroladores_1_1ControladorEstadisticas.html", null ],
    [ "ServidorMetadataDeAudios::capacontroladores::ControladorMetadatos", "structServidorMetadataDeAudios_1_1capacontroladores_1_1ControladorMetadatos.html", null ],
    [ "Cliente::capacontroladores::ControladorReproduccion", "structCliente_1_1capacontroladores_1_1ControladorReproduccion.html", null ],
    [ "ServidorDeAudios::fachada::FachadaAlmacenamiento", "structServidorDeAudios_1_1fachada_1_1FachadaAlmacenamiento.html", null ],
    [ "Administrador::fachada::FachadaAudios", "structAdministrador_1_1fachada_1_1FachadaAudios.html", null ],
    [ "ServidorDeEstadisticas::fachada::FachadaEstadisticas", "structServidorDeEstadisticas_1_1fachada_1_1FachadaEstadisticas.html", null ],
    [ "Cliente::fachada::FachadaMetadatos", "structCliente_1_1fachada_1_1FachadaMetadatos.html", null ],
    [ "ServidorMetadataDeAudios::fachada::FachadaMetadatos", "structServidorMetadataDeAudios_1_1fachada_1_1FachadaMetadatos.html", null ],
    [ "Cliente::fachada::FachadaStreaming", "structCliente_1_1fachada_1_1FachadaStreaming.html", null ],
    [ "ServidorDeStreaming::fachada::FachadaStreaming", "structServidorDeStreaming_1_1fachada_1_1FachadaStreaming.html", null ],
    [ "ServidorMetadataDeAudios::modelos::Metadato", "structServidorMetadataDeAudios_1_1modelos_1_1Metadato.html", null ],
    [ "Cliente::dtos::MetadatoDTO", "structCliente_1_1dtos_1_1MetadatoDTO.html", null ],
    [ "ServidorMetadataDeAudios::dtos::MetadatoDTOOutput", "structServidorMetadataDeAudios_1_1dtos_1_1MetadatoDTOOutput.html", null ],
    [ "Cliente::vistas::NavegadorVistas", "structCliente_1_1vistas_1_1NavegadorVistas.html", null ],
    [ "ServidorDeEstadisticas::componenteconexioncola::RabbitConsumidor", "structServidorDeEstadisticas_1_1componenteconexioncola_1_1RabbitConsumidor.html", null ],
    [ "ServidorDeStreaming::componenteconexioncola::RabbitPublicador", "structServidorDeStreaming_1_1componenteconexioncola_1_1RabbitPublicador.html", null ],
    [ "ServidorDeAudios::capaaccesodatos::RepositorioAudios", "structServidorDeAudios_1_1capaaccesodatos_1_1RepositorioAudios.html", null ],
    [ "ServidorDeStreaming::capaaccesodatos::RepositorioAudios", "structServidorDeStreaming_1_1capaaccesodatos_1_1RepositorioAudios.html", null ],
    [ "ServidorMetadataDeAudios::capaaccesoadatos::RepositorioAudios", "structServidorMetadataDeAudios_1_1capaaccesoadatos_1_1RepositorioAudios.html", null ],
    [ "ServidorDeEstadisticas::capaaccesodatos::RepositorioEstadisticas", "structServidorDeEstadisticas_1_1capaaccesodatos_1_1RepositorioEstadisticas.html", null ],
    [ "ServidorMetadataDeAudios::capaaccesoadatos::RepositorioTiposAudio", "structServidorMetadataDeAudios_1_1capaaccesoadatos_1_1RepositorioTiposAudio.html", null ],
    [ "ServidorDeEstadisticas::modelos::Reproduccion", "structServidorDeEstadisticas_1_1modelos_1_1Reproduccion.html", null ],
    [ "ServidorDeEstadisticas::dtos::ReproduccionDTOInput", "structServidorDeEstadisticas_1_1dtos_1_1ReproduccionDTOInput.html", null ],
    [ "ServidorDeStreaming::dtos::ReproduccionDTOOutput", "structServidorDeStreaming_1_1dtos_1_1ReproduccionDTOOutput.html", null ],
    [ "Cliente::utilidades::Reproductor", "structCliente_1_1utilidades_1_1Reproductor.html", null ],
    [ "Administrador::dtos::RespuestaErrorDTO", "structAdministrador_1_1dtos_1_1RespuestaErrorDTO.html", null ],
    [ "Cliente::dtos::RespuestaErrorDTO", "structCliente_1_1dtos_1_1RespuestaErrorDTO.html", null ],
    [ "ServidorDeAudios::dtos::RespuestaErrorDTOOutput", "structServidorDeAudios_1_1dtos_1_1RespuestaErrorDTOOutput.html", null ],
    [ "ServidorMetadataDeAudios::dtos::RespuestaErrorDTOOutput", "structServidorMetadataDeAudios_1_1dtos_1_1RespuestaErrorDTOOutput.html", null ],
    [ "ServidorDeEstadisticas::modelos::ResumenEstadisticas", "structServidorDeEstadisticas_1_1modelos_1_1ResumenEstadisticas.html", null ],
    [ "Cliente::capacontroladores::SesionReproduccion", "structCliente_1_1capacontroladores_1_1SesionReproduccion.html", null ],
    [ "ServidorMetadataDeAudios::modelos::TipoAudio", "structServidorMetadataDeAudios_1_1modelos_1_1TipoAudio.html", null ],
    [ "Cliente::dtos::TipoAudioDTO", "structCliente_1_1dtos_1_1TipoAudioDTO.html", null ],
    [ "ServidorMetadataDeAudios::dtos::TipoAudioDTOOutput", "structServidorMetadataDeAudios_1_1dtos_1_1TipoAudioDTOOutput.html", null ],
    [ "pb::UnimplementedAudioServiceServer", null, [
      [ "ServidorDeStreaming::capacontroladores::ControladorStreaming", "structServidorDeStreaming_1_1capacontroladores_1_1ControladorStreaming.html", null ]
    ] ]
];