// Contrato del servicio gRPC de streaming de audio.
// Los mensajes AudioRequest y AudioChunk actúan como DTOs que viajan en
// formato protobuffer entre el cliente y el servidor de streaming.
// Generación de stubs: protoc --go_out=. --go-grpc_out=. audio.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: audio.proto

package serviciosAudio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / Petición de reproducción de un audio.
type AudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"` ///< Nombre del archivo mp3 a reproducir.
	IdAudio       int32                  `protobuf:"varint,2,opt,name=idAudio,proto3" json:"idAudio,omitempty"`  ///< Identificador del audio en el servidor de metadatos.
	Titulo        string                 `protobuf:"bytes,3,opt,name=titulo,proto3" json:"titulo,omitempty"`     ///< Título del audio (para estadísticas).
	Tipo          string                 `protobuf:"bytes,4,opt,name=tipo,proto3" json:"tipo,omitempty"`         ///< Nombre del tipo de audio (para estadísticas).
	Usuario       string                 `protobuf:"bytes,5,opt,name=usuario,proto3" json:"usuario,omitempty"`   ///< Usuario que reproduce el audio.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioRequest) Reset() {
	*x = AudioRequest{}
	mi := &file_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioRequest) ProtoMessage() {}

func (x *AudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioRequest.ProtoReflect.Descriptor instead.
func (*AudioRequest) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{0}
}

func (x *AudioRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AudioRequest) GetIdAudio() int32 {
	if x != nil {
		return x.IdAudio
	}
	return 0
}

func (x *AudioRequest) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *AudioRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *AudioRequest) GetUsuario() string {
	if x != nil {
		return x.Usuario
	}
	return ""
}

// / Fragmento del archivo de audio enviado por el servidor.
type AudioChunk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Data            []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                        ///< Bytes del fragmento de audio.
	NumeroFragmento int32                  `protobuf:"varint,2,opt,name=numeroFragmento,proto3" json:"numeroFragmento,omitempty"` ///< Número consecutivo del fragmento.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_audio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{1}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetNumeroFragmento() int32 {
	if x != nil {
		return x.NumeroFragmento
	}
	return 0
}

var File_audio_proto protoreflect.FileDescriptor

const file_audio_proto_rawDesc = "" +
	"\n" +
	"\vaudio.proto\x12\tservicios\"\x8a\x01\n" +
	"\fAudioRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\aidAudio\x18\x02 \x01(\x05R\aidAudio\x12\x16\n" +
	"\x06titulo\x18\x03 \x01(\tR\x06titulo\x12\x12\n" +
	"\x04tipo\x18\x04 \x01(\tR\x04tipo\x12\x18\n" +
	"\ausuario\x18\x05 \x01(\tR\ausuario\"J\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12(\n" +
	"\x0fnumeroFragmento\x18\x02 \x01(\x05R\x0fnumeroFragmento2O\n" +
	"\fAudioService\x12?\n" +
	"\vAudioStream\x12\x17.servicios.AudioRequest\x1a\x15.servicios.AudioChunk0\x01B\x11Z\x0f/serviciosAudiob\x06proto3"

var (
	file_audio_proto_rawDescOnce sync.Once
	file_audio_proto_rawDescData []byte
)

func file_audio_proto_rawDescGZIP() []byte {
	file_audio_proto_rawDescOnce.Do(func() {
		file_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_proto_rawDesc), len(file_audio_proto_rawDesc)))
	})
	return file_audio_proto_rawDescData
}

var file_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_audio_proto_goTypes = []any{
	(*AudioRequest)(nil), // 0: servicios.AudioRequest
	(*AudioChunk)(nil),   // 1: servicios.AudioChunk
}
var file_audio_proto_depIdxs = []int32{
	0, // 0: servicios.AudioService.AudioStream:input_type -> servicios.AudioRequest
	1, // 1: servicios.AudioService.AudioStream:output_type -> servicios.AudioChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audio_proto_init() }
func file_audio_proto_init() {
	if File_audio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_proto_rawDesc), len(file_audio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audio_proto_goTypes,
		DependencyIndexes: file_audio_proto_depIdxs,
		MessageInfos:      file_audio_proto_msgTypes,
	}.Build()
	File_audio_proto = out.File
	file_audio_proto_goTypes = nil
	file_audio_proto_depIdxs = nil
}
